apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "homelab.db.fullname" . }}
  labels:
    app: {{ template "homelab.db.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "homelab.db.fullname" . }}
  replicas: {{ .Values.replicaCount }} 
  template:
    metadata:
      labels:
        app: {{ template "homelab.db.fullname" . }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - protocol: TCP
          containerPort: {{ .Values.service.targetPort }}
        {{- if gt (len .Values.secrets) 0}}
        env:
          {{- $fullname := include "homelab.db.fullname" . }}
          {{- range $name, $value := .Values.secrets }}
          - name: {{ $name }}
            valueFrom:
              secretKeyRef:
                name: {{ $fullname }}-secret
                key: {{ $name }}
          {{- end }}
        {{- end }}
        {{- range .Values.volumes }}
        volumeMounts:
          - name: {{ .name }}-db-storage
            mountPath: {{ .mountPath }}
        {{- end }}
      {{- range .Values.volumes }}
      volumes:
        - name: {{ .name }}-db-storage
          persistentVolumeClaim:
            claimName: {{ .name }}
      {{- end }}
