{{- if gt (len .Values.secrets) 0 -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "homelab.db.fullname" . }}-secret
stringData:
    {{ .Values.secrets | toYaml | nindent 2 }}
{{- end -}}