{{- if gt (len .Values.configmap) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homelab.fullname" . }}-configmap
  labels:
    {{- include "homelab.labels" . | nindent 4 }} 
  {{- if gt (len .Values.global.annotations) 0 }}
  annotations:
    {{- include "homelab.annotations" . | nindent 4 }}
  {{- end }}
data:
  {{- .Values.configmap | toYaml | nindent 2 -}}
{{- end -}}
