{{- if and .Values.ingress.enabled .Values.ingress.tls -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "homelab.fullname" . }}-certificate
  labels:
    {{- include "homelab.labels" . | nindent 4 }} 
  {{- if gt (len .Values.global.annotations) 0 }}
  annotations:
    {{- include "homelab.annotations" . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "homelab.fullname" . }}-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.ingress.clusterIssuer }}
  dnsNames:
    - {{ .Values.ingress.host | quote }}
{{- end -}}
