{{- if gt (len .Values.configmap) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homelab.fullname" . }}-configmap
  {{ include "homelab.labels" . }} 
  {{- include "homelab.annotations" . }}
data:
  {{- .Values.configmap | toYaml | nindent 2 -}}
{{- end -}}
