{{- if gt (len .Values.configmap) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "homelab.fullname" .}}-configmap
data:
    {{- .Values.configmap | toYaml | nindent 2 -}}
{{- end -}}