{{- if gt (len .Values.secrets) 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homelab.fullname" . }}-secret
  labels:
    {{- include "homelab.labels" . | nindent 4 }} 
  {{- if gt (len .Values.global.annotations) 0 }}
  annotations:
    {{- include "homelab.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- .Values.secrets | toYaml | nindent 2 }}
{{- end -}}
