{{- if gt (len .Values.secrets) 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homelab.fullname" . }}-secret
  {{ include "homelab.labels" . }} 
  {{- include "homelab.annotations" . }}
type: Opaque
stringData:
  {{- .Values.secrets | toYaml | nindent 2 }}
{{- end -}}
