name: Release Helm Chart

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Create Helm Release
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          packages_with_index: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Host pkl modules with pages
        run: |
          git fetch
          git checkout gh-pages
          git checkout master -- charts/homelab-charts/Chart.pkl charts/homelab-charts/values.pkl
          mv charts/homelab-charts/*.pkl .
          rm -r charts
          git add -A
          git diff-index --quiet HEAD || git commit -am "moved pkl modules to gh-pages"
          git push origin gh-pages
